### ISSUE TITLE
Add an experimental link to the installer

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/impactdevelopment.github.io#10]
To promote testing of the installer and reduce the burden on support helping users to manually install impact, we should prominently include a link to download the installer.

We should still say that it is experimental, but we should probably show it before the legacy downloads.

**Comment by 2b2tQueueProject** [comment]
⬆️

**Comment by leijurv** [comment]
in my opinion we should first throw in on #releases or #announcements (without at everyone) as a preprealpha or whatever

call it infdev or whatever

**Comment by EvilSourcerer** [comment]
open source it before release for additional improvements?

**Comment by LeafHacker** [comment]
It will be open sourced as soon as it has the required docs added to the repo. This isn't a blocker for that, nor vice versa.

**Comment by LeafHacker** [comment]
Yeah, if you think it should be soft-released on github first that's fine. Although I don't see why we shouldn't also show it as an experimental option on the website.

**Comment by leijurv** [comment]
weweased


adding a link on the site is probably good as soon as a jar is up

should probably direct link to /releases tho
