### ISSUE TITLE
The emoji looks gay on windows use png when

### ISSUE THREAD

**Issue by SpicyBigGithub** [ImpactDevelopment/impactdevelopment.github.io#11]
![Capture-1](https://user-images.githubusercontent.com/36968617/57974397-55497700-7985-11e9-90e0-ba1f117f9e1e.PNG)

**Comment by EvilSourcerer** [comment]
this should be an issue in the launcher repo when it's public, not here.

**Comment by LeafHacker** [comment]
This is off topic for the website.

**Comment by SpicyBigGithub** [comment]
Gay
