### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/impactdevelopment.github.io#16]
https://github.com/ImpactDevelopment/impactdevelopment.github.io/commit/a30da8905b5085ba6e165f483165a9a242be305d

this but again

**Comment by LeafHacker** [comment]
Spent an hour at 2am looking at a icon gen script in dc1384a61f8da6f4d607cc7037f7008831b2d323

**Comment by CodyJasonBennett** [comment]
Possible fix from [my pull request](https://github.com/ImpactDevelopment/impactdevelopment.github.io/pull/20).

The website has all of your icons and social meta, fully optimized.

It is also a progressive web app capable of running while the user is offline and returning with site content when they visit the site's URL, again offline.

This was done as a thank you to Brady with his support to [BattleBots development](https://github.com/CodyJasonBennett/BattleBots) with me.

![social-image](https://user-images.githubusercontent.com/23324155/60402281-11848880-9b53-11e9-95c7-978cd2ae66f2.png)

**Comment by LeafHacker** [comment]
Fixed in 5a84d1cc4b245b7693264dcff3aec9c01ff0e85e
