### ISSUE TITLE
[BUG] Changelog Page

### ISSUE THREAD

**Issue by angeleslos** [ImpactDevelopment/impactdevelopment.github.io#27]
On the changelog page on impactdevelopment.github.io, when you click on the Impact logo, it redirects you to a 404 message.

**Comment by LeafHacker** [comment]
The [Impact](https://impactdevelopment.github.io/Impact/) link is automatically generated by GitHub when it renders the [markdown]() into HTML. It links to `/Impact` but there is nothing there. I'll add a redirect page there or something I guess.
